with open("index.html", "r", encoding="utf-8") as f:
    lines = f.readlines()

# 身份列表从第1450行开始（索引1449），到第1519行结束（索引1518）
# 替换成两级选择
start_line = 1449  # <!-- 身份列表 -->
end_line = 1518    # 身份列表的最后一个</div>

new_lines = [
    "            <!-- 身份列表 -->\n",
    '            <div class="p-6 overflow-y-auto max-h-[65vh]">\n',
    "                <!-- 第一步：选择行业 -->\n",
    '                <div class="mb-8">\n',
    '                    <div class="flex items-center gap-2 mb-4">\n',
    '                        <span class="w-6 h-6 bg-gray-900 text-white rounded-full flex items-center justify-center text-xs font-bold">1</span>\n',
    '                        <h4 class="font-semibold text-gray-900">选择行业</h4>\n',
    "                    </div>\n",
    '                    <div class="grid grid-cols-2 gap-3">\n',
    '                        <button onclick="selectIndustry(\'物流供应链\')" class="industry-option w-full text-left px-4 py-3 border border-gray-200 rounded-xl hover:border-gray-900 hover:bg-gray-50 transition-all">\n',
    '                            <div class="flex items-center gap-3">\n',
    '                                <span class="text-xl">🚚</span>\n',
    '                                <span class="font-medium text-gray-900">物流供应链</span>\n',
    "                            </div>\n",
    "                        </button>\n",
    '                        <button onclick="selectIndustry(\'广告营销\')" class="industry-option w-full text-left px-4 py-3 border border-gray-200 rounded-xl hover:border-gray-900 hover:bg-gray-50 transition-all">\n',
    '                            <div class="flex items-center gap-3">\n',
    '                                <span class="text-xl">📢</span>\n',
    '                                <span class="font-medium text-gray-900">广告营销</span>\n',
    "                            </div>\n",
    "                        </button>\n",
    '                        <button onclick="selectIndustry(\'科技云计算\')" class="industry-option w-full text-left px-4 py-3 border border-gray-200 rounded-xl hover:border-gray-900 hover:bg-gray-50 transition-all">\n',
    '                            <div class="flex items-center gap-3">\n',
    '                                <span class="text-xl">💻</span>\n',
    '                                <span class="font-medium text-gray-900">科技/云计算</span>\n',
    "                            </div>\n",
    "                        </button>\n",
    '                        <button onclick="selectIndustry(\'金融\')" class="industry-option w-full text-left px-4 py-3 border border-gray-200 rounded-xl hover:border-gray-900 hover:bg-gray-50 transition-all">\n',
    '                            <div class="flex items-center gap-3">\n',
    '                                <span class="text-xl">💰</span>\n',
    '                                <span class="font-medium text-gray-900">金融</span>\n',
    "                            </div>\n",
    "                        </button>\n",
    '                        <button onclick="selectIndustry(\'医疗健康\')" class="industry-option w-full text-left px-4 py-3 border border-gray-200 rounded-xl hover:border-gray-900 hover:bg-gray-50 transition-all">\n',
    '                            <div class="flex items-center gap-3">\n',
    '                                <span class="text-xl">🏥</span>\n',
    '                                <span class="font-medium text-gray-900">医疗健康</span>\n',
    "                            </div>\n",
    "                        </button>\n",
    '                        <button onclick="selectIndustry(\'制造业\')" class="industry-option w-full text-left px-4 py-3 border border-gray-200 rounded-xl hover:border-gray-900 hover:bg-gray-50 transition-all">\n',
    '                            <div class="flex items-center gap-3">\n',
    '                                <span class="text-xl">🏭</span>\n',
    '                                <span class="font-medium text-gray-900">制造业</span>\n',
    "                            </div>\n",
    "                        </button>\n",
    '                        <button onclick="selectIndustry(\'零售电商\')" class="industry-option w-full text-left px-4 py-3 border border-gray-200 rounded-xl hover:border-gray-900 hover:bg-gray-50 transition-all">\n',
    '                            <div class="flex items-center gap-3">\n',
    '                                <span class="text-xl">🛒</span>\n',
    '                                <span class="font-medium text-gray-900">零售电商</span>\n',
    "                            </div>\n",
    "                        </button>\n",
    '                        <button onclick="selectIndustry(\'政企\')" class="industry-option w-full text-left px-4 py-3 border border-gray-200 rounded-xl hover:border-gray-900 hover:bg-gray-50 transition-all">\n',
    '                            <div class="flex items-center gap-3">\n',
    '                                <span class="text-xl">🏛️</span>\n',
    '                                <span class="font-medium text-gray-900">政企</span>\n',
    "                            </div>\n",
    "                        </button>\n",
    "                    </div>\n",
    "                </div>\n",
    "                \n",
    "                <!-- 第二步：选择销售类型 -->\n",
    '                <div id="sales-type-section" class="opacity-50 pointer-events-none">\n',
    '                    <div class="flex items-center gap-2 mb-4">\n',
    '                        <span id="step2-badge" class="w-6 h-6 bg-gray-300 text-white rounded-full flex items-center justify-center text-xs font-bold">2</span>\n',
    '                        <h4 class="font-semibold text-gray-900">选择销售类型</h4>\n',
    "                    </div>\n",
    '                    <div class="space-y-3">\n',
    '                        <button onclick="selectSalesType(\'大客户销售\')" class="sales-type-option w-full text-left px-4 py-3 border border-gray-200 rounded-xl hover:border-gray-900 hover:bg-gray-50 transition-all">\n',
    '                            <div class="flex items-center gap-3">\n',
    '                                <i class="fa fa-building text-gray-500 w-5 text-center"></i>\n',
    '                                <div class="flex-1">\n',
    '                                    <div class="font-medium text-gray-900">大客户销售</div>\n',
    '                                    <div class="text-sm text-gray-500 mt-0.5">KA销售，负责头部企业客户，项目型销售</div>\n',
    "                                </div>\n",
    "                            </div>\n",
    "                        </button>\n",
    '                        <button onclick="selectSalesType(\'渠道销售\')" class="sales-type-option w-full text-left px-4 py-3 border border-gray-200 rounded-xl hover:border-gray-900 hover:bg-gray-50 transition-all">\n',
    '                            <div class="flex items-center gap-3">\n',
    '                                <i class="fa fa-sitemap text-gray-500 w-5 text-center"></i>\n',
    '                                <div class="flex-1">\n',
    '                                    <div class="font-medium text-gray-900">渠道销售</div>\n',
    '                                    <div class="text-sm text-gray-500 mt-0.5">代理商、合作伙伴、生态体系建设与管理</div>\n',
    "                                </div>\n",
    "                            </div>\n",
    "                        </button>\n",
    '                        <button onclick="selectSalesType(\'行业销售\')" class="sales-type-option w-full text-left px-4 py-3 border border-gray-200 rounded-xl hover:border-gray-900 hover:bg-gray-50 transition-all">\n',
    '                            <div class="flex items-center gap-3">\n',
    '                                <i class="fa fa-industry text-gray-500 w-5 text-center"></i>\n',
    '                                <div class="flex-1">\n',
    '                                    <div class="font-medium text-gray-900">行业销售</div>\n',
    '                                    <div class="text-sm text-gray-500 mt-0.5">垂直行业线深耕，懂行业懂客户</div>\n',
    "                                </div>\n",
    "                            </div>\n",
    "                        </button>\n",
    '                        <button onclick="selectSalesType(\'企业服务销售\')" class="sales-type-option w-full text-left px-4 py-3 border border-gray-200 rounded-xl hover:border-gray-900 hover:bg-gray-50 transition-all">\n',
    '                            <div class="flex items-center gap-3">\n',
    '                                <i class="fa fa-cloud text-gray-500 w-5 text-center"></i>\n',
    '                                <div class="flex-1">\n',
    '                                    <div class="font-medium text-gray-900">企业服务销售</div>\n',
    '                                    <div class="text-sm text-gray-500 mt-0.5">SaaS、软件、企业解决方案</div>\n',
    "                                </div>\n",
    "                            </div>\n",
    "                        </button>\n",
    '                        <button onclick="selectSalesType(\'解决方案销售\')" class="sales-type-option w-full text-left px-4 py-3 border border-gray-200 rounded-xl hover:border-gray-900 hover:bg-gray-50 transition-all">\n',
    '                            <div class="flex items-center gap-3">\n',
    '                                <i class="fa fa-lightbulb-o text-gray-500 w-5 text-center"></i>\n',
    '                                <div class="flex-1">\n',
    '                                    <div class="font-medium text-gray-900">解决方案销售</div>\n',
    '                                    <div class="text-sm text-gray-500 mt-0.5">方案咨询、复杂项目、价值销售</div>\n',
    "                                </div>\n",
    "                            </div>\n",
    "                        </button>\n",
    "                    </div>\n",
    "                </div>\n",
    "            </div>\n",
    "            \n",
    "            <!-- 底部确认按钮 -->\n",
    '            <div class="p-6 border-t border-gray-200">\n',
    '                <button id="confirm-identity-btn" onclick="confirmIdentity()" disabled class="w-full py-3 bg-gray-300 text-white rounded-xl font-medium cursor-not-allowed transition-all">\n',
    "                    请先选择行业和销售类型\n",
    "                </button>\n",
    "            </div>\n",
]

# 替换
result = lines[:start_line] + new_lines + lines[end_line+1:]

with open("index.html", "w", encoding="utf-8") as f:
    f.writelines(result)

print(f"替换完成！替换了 {end_line - start_line + 1} 行，新增了 {len(new_lines)} 行")
